### ISSUE TITLE
How do you save? 

### ISSUE THREAD

**Issue by MrMangoCango** [iNDS-Team/iNDS#147]
Sorry if this is a dumb question. I have auto save turned on but see no way to manually save.

**Comment by FrederickGeek8** [comment]
There are two ways to save:
1. (Recommended) Just save normally in your game and the save will be there when you click "Launch Normally"
2. (Not recommended) You can click "Save State" in the Settings menu when you launch a game to save a snapshot of the game. This is not recommended because these saves can break between updates to the emulator core (though I don't think that will occur anytime in the near future)

Let me know if you have any further questions
