### ISSUE TITLE
Does not display properly on ipad pro11

### ISSUE THREAD

**Issue by a041461** [iNDS-Team/iNDS#149]
**Describe the bug**
Can't run normally on ipad pro 11.The screen display is incomplete and some buttons are missing.

**To Reproduce**
1. Use Xcode install inds
2. Click on the inds
3. Run the nds game

**Screenshots**
![WeChat Image_20191223181335](https://user-images.githubusercontent.com/37897240/71351970-006f7e00-25b0-11ea-9011-92342e02416d.jpg)
![WeChat Image_20191223181344](https://user-images.githubusercontent.com/37897240/71351972-006f7e00-25b0-11ea-8089-080c1eb34dc6.jpg)
![WeChat Image_20191223181351](https://user-images.githubusercontent.com/37897240/71351973-006f7e00-25b0-11ea-8f36-29bb9292553a.jpg)

**Smartphone (please complete the following information):**
 - Device: ipad pro 11
 - OS: ios 13.1.3
 - Version 1.10.5 

**Additional context**
The game can run but cant show rightside screen and button. And can use slipe down to open the game and setting page.

**Comment by FrederickGeek8** [comment]
That's a very weird way it's presenting itself, I wonder what's causing that. I'll check it out soon since I'm getting an iPad Pro 11 in a few days. 

Just for a comparison, this is what it should look like (running in an iPad Pro 11 simulator).
![image](https://user-images.githubusercontent.com/774597/71361918-b0fa6500-2551-11ea-9ac3-08407fe3e4b2.png)

**Comment by FrederickGeek8** [comment]
I wonder if it has something to do with the language setting. That's Simplified Chinese, right?

**Comment by FrederickGeek8** [comment]
Tell me if the latest commit doesn't help

**Comment by a041461** [comment]
Yeah! It works! 
Thx for the quick response!
