### ISSUE TITLE
I’m stupid for asking 

### ISSUE THREAD

**Issue by Spiderdoom** [iNDS-Team/iNDS#150]
How do i use the mic please? I know it’s a dumb question but i don’t know how to.

**Comment by FrederickGeek8** [comment]
The microphone is enabled by default in iNDS. If you believe you might have disabled it, you can enable it again in the Settings menu. If its not working, it could be because you accidentally denied iNDS microphone access after launching it for the first time. If this is the case, I found [this guide](https://9to5mac.com/2018/04/23/how-to-check-apps-access-to-iphone-camera-microphone/) that might help you.
