### ISSUE TITLE
Enabling the audio after disabling it doesn't restore the audio

### ISSUE THREAD

**Issue by Wh0ba** [iNDS-Team/iNDS#35]
After disabling the audio using the switch in the settings the sound is muted
When enabling it again without restarting the app the sound doesn't return even if I tried changing the ROM 
The only solution is to restart the app

**Comment by FrederickGeek8** [comment]
I was able to reproduce this with some tweaks on the original instructions:

1. Disable sound without any ROM loaded (on the ROM selection screen)
2. Load a ROM
3. Open settings and enable sound
4. Observe that sound no longer works

**Comment by FrederickGeek8** [comment]
I seem to have fixed it but I don't really understand why it works. To me, it appears to be a bug with DeSmuME rather than something that we did (although it could be argued that we are doing something weird with enabling/disabling the sound).

It appears that the SPU (Sound Processing Unit) needs to "kickstarted" when we are initializing the ROM. If we disable the sound before starting up a ROM, then we never "kickstart" the SPU. I solved this in a rather hacky way by just pinging the SPU whenever we disable the sound, which shouldn't have any weird side-effects (besides possibly hearing audio for a split-second.

You can check out the change on my fork [FrederickGeek8/iNDS/tree/fix-35](https://github.com/FrederickGeek8/iNDS/tree/fix-35)

**Comment by FrederickGeek8** [comment]
Actually, I might have a better idea. This bug still exists (it appears), if you launch the game with your system audio muted. Perhaps it would be best to kickstart the audio when initializing the ROM instead.
