### ISSUE TITLE
[Sound]No sound whenever lauch the game

### ISSUE THREAD

**Issue by BrightSoulXYHY** [iNDS-Team/iNDS#80]
**Describe the bug**
No sound whenever lauch the game. i try to reinstall & reimport rom to solve it. But it doesn't work.

**To Reproduce**
I use Ipad pro 9.7 of ios 11.4.1.
and ipad is not jailbreak(maybe)
i install by visiting www.iosem.us/app/install/inds.html
the version of inds is 1.8.2

**Expected behavior**
the sound need to output correctly

**Smartphone (please complete the following information):**
 - Device: ipad pro 9.7
 - OS: ios 11.4..1

**Comment by nanogram** [comment]
Try the latest version plz.

**Comment by FrederickGeek8** [comment]
I would advise you to update your version of iNDS as that version is very old and there have been several updates that have included audio fixes since then. Seeing as the where you downloaded it from does not support a more modern version, I would advise you to research somewhere else for an update. In the past, I've seen users use [BuildStore, Cydia Impactor](https://github.com/iNDS-Team/iNDS/wiki/Building-&-Installing-iNDS-(Jailed)#third-party), AppValley, as well as some others. I'm closing this for the time being as you are inquiring about an issue which has already been fixed.
